templates/accounts.yaml
This is an attempt to narrow the read-only permissions. Currently any account that is part of AWSIAMAllUsersGroup has the global read-only policy. In order to make a more streamlined Service Catalog experience, it requires that the permissions for the group be pared back. I did this in AWSIAMAllUsersGroup and I believe removing `arn:aws:iam::aws:policy/ReadOnlyAccess` there is the right thing to do. However, perhaps the additional policies should be added to '${AWS::Region}-sc-enduser-iam-EndUserGroupName' rather than AWSIAMAllUsersGroup.
The end result is that we still have four user tiers:
1. SC users, most restricted
2. Developer Users, who have Power User 
3. Admin
4. Billing
=> First pass at more restricted read-only permissions for AWSIAMAllUsersGroup

README.md, config/prod/sc-ec2vpc-launchrole.yaml, config/prod/sc-ecs-launchrole.yaml, config/prod/sc-emr-launchrole.yaml, config/prod/sc-enduser-iam.yaml, config/prod/sc-glue-launchrole.yaml, config/prod/sc-portfolio-ec2.yaml, config/prod/sc-portfolio-s3.yaml, config/prod/sc-portfolio-vpc.yaml, config/prod/sc-rds-launchrole.yaml, config/prod/sc-s3-launchrole.yaml, config/prod/sc-serverless-launchrole.yaml
swap aws-service-catalog-reference-architectures for scipoolprod-sc-lib-infra after creating the latter as a new template library repo
=> Replace references to template lib 

config/prod/sc-portfolio-s3-basic.yaml, config/prod/sc-portfolio-s3.yaml
The S3 portfolios were using the EC2 launch role. Update to use SCS3LaunchRole.
=> Correct launch role in S3 portfolios

config/prod/cfn-ssm-param-permission.yaml, templates/cfn-ssm-param-permission.yaml
This grants lambda invoke permission for the SsmParam function to SCEC2LaunchRole. I placed this in scipoolprod-infra as I can't put this permission with the lambda template in aws-infra since it depends on a template in scipoolprod-sc-lib-infra and the lambda function is finally instantiated in scipoolprod-infra. Also, we may want to use SsmParam down the road outside of Service Catalog.
=> SCEC2LaunchRole invoke permission for SsmParam

config/prod/sc-portfolio-ec2-development.yaml, config/prod/sc-portfolio-ec2.yaml, config/prod/sc-portfolio-s3-basic-development.yaml, config/prod/sc-portfolio-s3-basic.yaml
- config to instantiate development portfolio for EC2
- config to instantiate development portfolio for S3
- update existing EC2 and S3 portfolios to use new treatment of principals
- This PR depends on https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/53
- This PR also depends on https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/54
=> Add configs for development EC2 and S3 portfolios

config/prod/cfn-tag-instance-policy.yaml, templates/cfn-tag-instance-policy.yaml
This policy gives permission to search provisioned products. It will be applied to the `InstanceRole` in service catalog library EC2 products. This permission is necessary to look up provisioned products, filtering on stack id, to retrieve the name a user assigned to a provisioned product when using the Service Catalog. That name will then be used to tag their instance. This is the first of two PRs for SC-29.
=> Add policy that allows searching provisioned products

config/dev/sc-tag-options-dev.yaml, templates/sc-tag-options-dev.j2
split templates to get around weird error that says the ref doesn't exist even though it is in same template
=> Fix for continued tag options difficulty -- just split templates

config/prod/sc-accounts.yaml
Removes scaccounts
The user accounts in this have been decoupled from the stack
When we are ready to transition to using the synapse login only, we will need to remove those manually.
=> Remove scaccounts stack

config/config.yaml, config/dev/sc-portfolio-ec2-development-tthyer.yaml, config/dev/sc-portfolio-ec2-development.yaml, config/dev/sc-portfolio-s3-basic-development.yaml, config/prod/AccountAlertTopics.yaml, config/prod/sc-ec2-actions.yaml, config/prod/sc-ec2vpc-launchrole.yaml, config/prod/sc-enduser-development-iam.yaml, config/prod/sc-enduser-iam.yaml, config/prod/sc-portfolio-ec2.yaml, config/prod/sc-portfolio-s3-basic.yaml, config/prod/sc-s3-launchrole.yaml
Makes string used in urls for location of service catalog library configurable 
This will be followed up with a PR to replace the before_create and before_update hooks with the single before_launch hook.
=> Make reference to sc library name configurable

config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/develop/sc-product-ec2-linux-jumpcloud.yaml, config/develop/sc-product-ec2-windows-jumpcloud.yaml, config/develop/sc-product-s3-private-enc.yaml, config/develop/sc-product-s3-synapse.yaml, config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/prod/sc-product-ec2-linux-jumpcloud.yaml, config/prod/sc-product-s3-private-enc.yaml, config/prod/sc-product-s3-synapse.yaml
Adds the portfolios ids that are required when configuring a product stack. This PR is dependent upon Sage-Bionetworks/service-catalog-library#143.
=> Supply required PortfolioId in product parameters

config/develop/cfn-sc-actions-provider.yaml, config/prod/cfn-sc-actions-provider.yaml
The cfn-sc-actions-provider moved and now deploys to a different bucket
path so we need to update the reference to the new location.
The custom resource moved to
https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider
There was a bug in the underlying lambda build,  it's fixed with PR
https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider/pull/2
This build depends on that PR.
=> Update reference to custom resource

config/develop/get-role-policy.yaml, config/develop/sc-remoting-policy.yaml
This adds a new stack to the Service Catalog for remote access policies used when creating instances. I plan to revise tagging policies and include them in this stack rather than what we use in essentials.
Passes pre-commit
Related to https://github.com/Sage-Bionetworks/service-catalog-library/pull/150
=> Build new policy stack in SC

config/develop/get-role-policy.yaml
This PR should fix the resolution error that causes the Travis deploy step to fail. The template_path variable did not match that curl command output. Maybe there's a way to have sceptre do that substitution?
=> SC 54.4 Match template path with output of hook

config/develop/maintenance.yaml
This adds a scheduled task to the develop account based on the template from aws-infra.
Related: https://github.com/Sage-Bionetworks/aws-infra/pull/244
=> Add maintenance task to devel

config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/develop/sc-product-ec2-linux-jumpcloud.yaml, config/develop/sc-product-ec2-windows-jumpcloud.yaml, config/develop/sc-product-s3-private-enc.yaml, config/develop/sc-product-s3-synapse.yaml, config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/prod/sc-product-ec2-linux-jumpcloud.yaml, config/prod/sc-product-ec2-windows-jumpcloud.yaml, config/prod/sc-product-s3-private-enc.yaml, config/prod/sc-product-s3-synapse.yaml
Removes the date param that was previously used to ensure product versions updated.
This PR should be merged prior to https://github.com/Sage-Bionetworks/service-catalog-library/pull/165.
=> Remove StackDatetime from product stack configurations

config/prod/get-role-policy.yaml
The region-get-role-policy-ReadAssumedRoleInformationPolicy export is missing from cfn in scipoolprod. See [SC-157](https://sagebionetworks.jira.com/projects/SC/issues/SC-157)
Will need to merge develop->prod after.
Passes pre-commit.
=> Add get-role-policy template to prod path

.travis.yml
Sceptre debug is too noisy and it's error messages are not that helpful.
Goting back to non debug log is actually more helpful.
=> turn off sceptre debug logs

.travis.yml, config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/develop/sc-product-ec2-linux-jumpcloud.yaml, config/develop/sc-product-ec2-windows-jumpcloud.yaml
This is a workaround for the  problem that arises from product versions
being replaced. To date we have found no other way to force updates than
to replace product versions. However, we are focused on doing so because
we’re developing. In production, we should release a version and freeze it,
and there is no problem with updates when adding a new version (appending
a new item to the version list).
This PR depends on PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/192
=> [SC-171] Make SC service actions sticky

config/develop/sc-portfolio-ec2-external.yaml, config/prod/sc-portfolio-ec2-external.yaml
The portfolio for external users referenced the wrong CFN template file.
Fix to use the correct one.
=> [SC-65] Fix template reference

templates/sc-ec2vpc-launchrole.yaml
grant the ability to invoke a lambda to the ec2 launch role
=> Add permission to invoke lambdas to SCEC2LaunchRole's SCLaunchPolicy

config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/develop/sc-product-ec2-linux-jumpcloud.yaml, config/develop/sc-product-ec2-windows-jumpcloud.yaml, config/develop/sc-product-s3-private-enc.yaml, config/develop/sc-product-s3-synapse.yaml, config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml, config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml, config/prod/sc-product-ec2-linux-jumpcloud.yaml, config/prod/sc-product-ec2-windows-jumpcloud.yaml, config/prod/sc-product-s3-private-enc.yaml, config/prod/sc-product-s3-synapse.yaml, templates/sc-product-ec2-linux-jumpcloud-notebook.yaml, templates/sc-product-ec2-linux-jumpcloud-workflows.yaml, templates/sc-product-ec2-linux-jumpcloud.yaml, templates/sc-product-ec2-windows-jumpcloud.yaml, templates/sc-product-s3-private-enc.yaml, templates/sc-product-s3-synapse.yaml
New tags were created in https://github.com/Sage-Bionetworks/service-catalog-library/tags
so now we can properly reference from a tagged directory of files in S3
The versions v1.0.0, v1.0.1, and v1.0.2 are all identical.  The idea
behind creating idential versions is so we can match the version of the
S3 bucket folder with the version on the file.  If we didn't create
multiple versions we would have to reference with `v1.0.0` for the
folder and `sc-ec2-linux-jumpcloud-v1.0.2.yaml` for the file which
would be pretty confusing. i.e.:
```
- Description: !Sub 'Fix to support multiple portfolios. Last updated at ${StackDatetime}.'
Info:
LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.0.0/ec2/sc-ec2-linux-jumpcloud-v1.0.2.yaml'
Name: 'v1.0.2'
```
Also I didn't wanted to keep the existing …
=> [SC-192] Refactor references to product templates

.pre-commit-config.yaml, config/develop/alb-notebook-access.yaml, templates/alb-notebook-access.yaml
This PR does a few things:
1. Creates an ALB and a policy that allows a lambda to add rules to it. This policy is exported in a role that can be imported by the lambda.
2. Creates a KMS key following our convention for administering the key (we may want to expand administration rights on this KMS key). There is an associated KMS read/decrypt policy and SSM parameter read policy that are included in the role for the lambda. The lambda function will need to recreate the OIDC auth step for every rule it adds to the ALB and so will need access to the ODIC client secret which will be an secret string in SSM.
3. Creates an SSL cert for an input sub.domain parameter. We already have wildcard certs at the root of a few domains, but I'm leaving this piece in place so we can define complete …
=> SC-135 ALB->Notebooks resources

config/develop/alb-notebook-access.yaml, templates/alb-notebook-access.yaml
This PR fixes the sceptre deployment, which had a name mismatch, and fixes the Route 53 CNAME record pointing to the ALB. The subdomain is made variable as a new input to the sceptre config.
=> Fix sceptre deploy and subdomain CNAME

templates/alb-notebook-access.yaml
This removes the EC2 Security Group from this template and [move it over here](https://github.com/Sage-Bionetworks/service-catalog-library/pull/213). The purpose is to keep the EC2 resources together with the EC2 template.
=> Move EC2 SG out of template

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
New version that will use the new alb-rule-making custom resource
Depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/214
Also depends on creating a tag when that ^^ is merged. Assuming next tag will be v1.1.1.
=> New version of notebook for alb-rule CR

config/develop/synapse-oidc-idp.yaml, config/prod/synapse-oidc-idp.yaml
The OIDC IDP provider has moved from Sage-Bionetworks to
Sage-Bionetworks-IT org.  Updating sceptre template to get
the lambda from new location.
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-oidc-idp/pull/1
=> [IT-876] reference oidc idp provider at new location

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml, templates/sc-product-ec2-linux-jumpcloud-workflows.yaml, templates/sc-product-ec2-linux-jumpcloud.yaml
Update products without jumpcloud integration.  The only product
that still contains jumpcloud integration is windows EC2.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/216
and a new v1.1.2 tag
=> [SC-100] update products

templates/alb-notebook-access.yaml
This PR adds the access logging service to the notebook-fronting ALB following [general AWS documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html). I think we will actually want to forward these logs to logcentral, however.
This PR is revised based on a discussion today. This will allow us to log locally to the account for the time being. I've revised the bucket policy and path.
=> Add ALB logging within account

templates/alb-notebook-access.yaml
There's a permissions policy or competition between calls that causes this build to fail. I'm planning to split out the resources the make it fail anyway, so that we can have more control over them with changing dependent stacks.
Reverts Sage-Bionetworks/scipool-infra#152
=> Revert "Add ALB logging within account"

config/develop/alb-notebook-access-logsbucket.yaml, config/prod/alb-notebook-access-logsbucket.yaml
Somehow the prior PR had a cfn header in a sceptre template. This fixes the deployment on top of a failing build.
=> Sceptre templates were malformed

config/develop/alb-notebook-access.yaml, config/prod/alb-notebook-access.yaml
The travis build is still failing because of a broken sceptre template from a different branch. This PR should fix.
=> Revised malformed sceptre config

config/develop/sc-tag-options-external.yaml, config/develop/sc-tag-options.yaml, config/prod/sc-tag-options-external.yaml, config/prod/sc-tag-options.yaml
We've decided that keeping tag options consistant for internal
and external users would simplify management of tags.
However we also want to distinguise what values are available to
external vs internal users. This PR targets tag option
values, external users will be required to set the Department
and Project tag however we will only allow one value for each
tag.
=> [SC-215] Target tag option values

config/develop/alb-notebook-access-logsbucket.yaml, config/develop/alb-notebook-access.yaml, config/develop/sc-tag-options-external.yaml, config/develop/sc-tag-options.yaml, config/prod/alb-notebook-access-logsbucket.yaml, config/prod/alb-notebook-access.yaml, config/prod/sc-tag-options-external.yaml, config/prod/sc-tag-options.yaml, templates/alb-notebook-access-logsbucket.yaml, templates/alb-notebook-access.yaml
Changes:
2eec777 (Khai Do, 2 minutes ago)
add comments to tag option deployments (#164)
e40fc02 (Khai Do, 12 minutes ago)
fix file reference (#163)
4e62d3e (Khai Do, 49 minutes ago)
Target tag option values (#154)
We've decided that keeping tag options consistant for internal
and
external users would simplify management of tags.
However we also want to
distinguise what values are available to
external vs internal users. This
PR targets tag option
values, external users will be required to set the
Department
and Project tag however we will only allow one value for each
tag.
6817c1b (Aaron Hayden, 30 hours ago)
Revised malformed sceptre config
c3163b0 (Aaron Hayden, 3 days ago)
Sceptre templates were malformed
51fd678 (Aaron Hayden, 3 days ago)
Add logsbucket template to prod sceptre config …
=> Update from develop to prod

.travis.yml
We set the "ReplaceProvisioningArtifacts" to false for the SC prod env
to prevent new product IDs from being created on every deployment which
is what we want. Since product IDs never change the template to associate
SC actions to products never runs on subsequent stack updates. This is
the reason why SC actions don't appear on newly added versions of a
SC product.
To fix this we need to dis-associate and re-associate SC actions on every
deployment.  This strategy is a work around for issue SC-26
Note: The dis-association will remove SC actions from the SC actions
menu for a short period of time.  This can cause 2 issues for the user:
1. user cannot access stop/start/restart because it has been
dis-associated before they clicked on the SC actions menu.
This is momentary because the …
=> [SC-219] Fix SC action associations

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml, templates/sc-product-ec2-linux-jumpcloud-workflows.yaml, templates/sc-product-ec2-linux-jumpcloud.yaml, templates/sc-product-ec2-windows-jumpcloud.yaml
This updates EC2 templates to use `service-catalog-library v1.1.3` which includes:
- Cfn signaling so products announce ready only when building is fully done
- Updated Windows Server 2016 AMI ID
Passes pre-commit
=> Update effected templates to service-catalog-library v1.1.3

templates/sc-product-ec2-windows-jumpcloud.yaml
We had removed version strings from product filepaths, but had not released a new version of the Windows product. This corrects the filepath name that broke the build.
Passes pre-commit.
=> Change file path on Windows products

templates/sc-ec2vpc-launchrole.yaml, templates/sc-s3-launchrole.yaml
SC launch of workflows product is failing because the launch roles are missing the ability to tag IAM roles, so add that permission to relevant policies.
=> [SC-226] Add iam:TagRole permission to launch policies

.cfnlintrc, config/develop/lambda-budgets.yaml, config/prod/lambda-budgets.yaml, templates/develop/lambda-budgets/budget-rules.yaml, templates/develop/lambda-budgets/thresholds.yaml, templates/prod/lambda-budgets/budget-rules.yaml, templates/prod/lambda-budgets/thresholds.yaml
This adds the lambda-budgets configuration for dev and prod. It depends on a new folder, "budgets", which contains configuration files for the lambda. The role in the configurations in different for dev and prod deliberately.
Depends on https://github.com/Sage-Bionetworks-IT/lambda-budgets/pull/5
=> [SC-88] Add lambda-budgets configuration

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml, templates/sc-product-ec2-linux-jumpcloud-workflows.yaml, templates/sc-product-ec2-linux-jumpcloud.yaml, templates/sc-product-ec2-windows-jumpcloud.yaml, templates/sc-product-s3-private-enc.yaml, templates/sc-product-s3-synapse.yaml
Updte SC libraries to use the cfn-cr-synapse-tagger custom resource[1]
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger
depends on Sage-Bionetworks/service-catalog-library#225
also depends on creating a Sage-Bionetworks/service-catalog-library `v1.1.7` tag
=> [SC-190] Update SC libraries

config/develop/s3-cesspoolvpc-gateway-endpoint.yaml, config/prod/s3-internalpoolvpc-gateway-endpoint.yaml
[IT-957]
This PR adds VPC gateway endpoints in cesspoolvpc and internalpoolvpc. This should ensure that we don't incur NAT charges when pushing data from EC2 instances in these VPCs to S3.
[IT-957]: https://sagebionetworks.jira.com/browse/IT-957
=> IT-957: Add VPC gateway endpoints

config/develop/cfn-cr-synapse-tagger.yaml, config/prod/cfn-cr-synapse-tagger.yaml
update cfn-cr-synapse-tagger to ver 0.0.2 which contains the
functionality to apply a teamId tag to SC resources[1]
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger/commit/9e8f6cafee6c94bfbf68f906da7b0403d5ba3386
=> [SC-207] Update synpase tagger

config/develop/cfn-cr-synapse-tagger.yaml, config/prod/cfn-cr-synapse-tagger.yaml
update cfn-cr-synapse-tagger to ver 0.0.3 which contains the
change to exclude some Synapse userProfile data[1]
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger/commit/121da734d5ca2ce9377101822bc1c6774fc564f6
=> Update synpase tagger version

config/develop/park-my-cloud.yaml, config/prod/park-my-cloud.yaml
We no longer use PMC to manage EC2 instances.  We now use
the SC actions feature to start/stop/restart instances.
=> Remove integration with park my cloud

config/develop/cfn-explode-macro.yaml, config/prod/cfn-explode-macro.yaml
I don't remember why we needed this macro in the past but we definately
do not use it anymore.
=> Remove the explode macro

config/develop/sc-enduser-iam.yaml, config/prod/sc-enduser-iam.yaml, config/strides/sc-enduser-iam.yaml, templates/sc-enduser-iam.yaml
We added a `role/synapse-login-strides-InstanceRole` which doesn't match
the ServiceCatalogEndusers role regex which caused the synapse user login
to fail with the following message:
```
Error:
com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException:
User: arn:aws:sts::423819316185:assumed-role/synapse-login-strides-InstanceRole-NMC6P2A74X1J/i-0e2aded9709059ff3
is not authorized to perform: sts:TagSession on resource: arn:aws:iam::423819316185:role/ServiceCatalogEndusers
(Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: db23c747-3cb9-4920-8d0d-93e55886357c; Proxy: null)
```
Refactor the template to pass in the exact synapse login instance role ARN instead of
using pattern matching. 
depends on …
=> [SC-235] Fix permission for strides account

.travis.yml
This is a change to the deployment strategy and workflow. Intead of
deploying to the equivalent branch that code is merged into we group
deployments into two buckets, dev and prod. When code is merged into
the development branch travis will deploy to the dev account (i.e.
scipooldev). When code is merged to the prod branch travis will deploy,
in parallel, to all prod accounts (i.e. scipoolprod, strides, etc..).
The goal is to make it easier and faster to deploy to production accounts.
=> Change deployment strategy

.travis.yml, config/develop/sc-tag-options-external.yaml, config/develop/sc-tag-options.yaml, config/prod/sc-tag-options-external.yaml, config/prod/sc-tag-options.yaml, config/strides/sc-tag-options-external.yaml, config/strides/sc-tag-options.yaml, sc-tag-options/external/Departments.json, sc-tag-options/external/Projects.json, sc-tag-options/internal/Departments.json, sc-tag-options/internal/Projects.json
This is a 2nd attempt at commit a7f72bd6b3. The first attempt failed
because using the Sceptre file_contents resolver[1] passed the file
content as a string to the parameter. The jinja template that processes
the parameter requires a list object.  The new and improved
Sceptre file resolver[2] fixes this by getting the contents of a json or
yaml file and passing it to the parameter as an object.
[1] https://sceptre.cloudreach.com/2.2.1/docs/resolvers.html#file-contents
[2] https://github.com/Sage-Bionetworks-IT/sceptre-file-resolver
depends on https://github.com/Sage-Bionetworks-IT/sceptre-file-resolver/pull/1
=> 2nd attempt at DRY tag options

config/develop/idp-marketplace-policy.yaml, config/develop/marketplace-dynamo.yaml, config/prod/idp-marketplace-policy.yaml, config/prod/marketplace-dynamo.yaml, config/strides/idp-marketplace-policy.yaml, config/strides/marketplace-dynamo.yaml, templates/idp-marketplace-policy.yaml, templates/marketplace-dynamo.yaml
The build broke:
https://travis-ci.org/github/Sage-Bionetworks/scipool-infra/jobs/739142121
and I traced it to the [definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html) of the Roles field in a managed policy declaration:  The Roles field is "The name (friendly name, not ARN) of the role to attach the policy to."
[synapse-login-aws-infra](https://github.com/Sage-Bionetworks/synapse-login-aws-infra/blob/develop/templates/app.yaml) exports both InstanceRole.Arn and InstanceRole. I am *assuming* that "InstanceRole" is the requisite "friendly name".
=> SC-254:  Managed policy uses 'friendly name' for Role, not Role ARN

templates/marketplace-dynamo.yaml
The dyamodb table ARN is needed by the cfn-cr-synapse-tagger in PR https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger/pull/19
=> [SC-255] output the marketplace dynamodb table ARN

config/develop/cfn-cr-synapse-tagger.yaml, config/prod/cfn-cr-synapse-tagger.yaml, config/strides/cfn-cr-synapse-tagger.yaml
This update depends on existing SSM parameters:
* `/service-catalog/TeamToRoleArnMap` - used to determine and apply the Synapse team tag
* `/service-catalog/MarketplaceProductCodeSC` - used to apply the service catalog
AWS Marketplace product code tag
It also depends on an existing marketpace subscriber Dynamo DB
=> Update cfn-cr-synapse-tagger version

config/develop/cfn-cr-synapse-tagger.yaml, config/prod/cfn-cr-synapse-tagger.yaml, config/strides/cfn-cr-synapse-tagger.yaml
This reverts commit ddc56d1f703a540cd700bc01ffc01edce634438b.
This fails in prod environments because the `MarketplaceProductCodeSC` env var
has not been setup in all environments yet.
=> Revert "Update cfn-cr-synapse-tagger version (#220)"

config/develop/cfn-cr-bucket-tagger.yaml, config/prod/cfn-cr-bucket-tagger.yaml, config/strides/cfn-cr-bucket-tagger.yaml
The cfn-cr-bucket-tagger is deprecated and has been replaced with
the cfn-cr-synapse-tagger
=> remove cfn-cr-bucket-tagger

templates/alb-notebook-access.yaml
This adds an SSL policy beyond the default to the notebook ALB and will not require replacement. 
It passes pre-commit, but I'm not able to validate the template or push it to a test env.
=> Add standard SSL policy

.travis.yml
Sceptre removed their "greedy file path" feature therefore we need to update the
way we deploy templates in order to use the latest version of sceptre.
=> [SC-293] use latest sceptre version
