Sage-Bionetworks/scipool-infra

config/prod/sc-ec2vpc-launchrole.yaml
config/prod/sc-ecs-launchrole.yaml
config/prod/sc-emr-launchrole.yaml
config/prod/sc-enduser-iam.yaml
config/prod/sc-glue-launchrole.yaml
config/prod/sc-rds-launchrole.yaml
config/prod/sc-s3-launchrole.yaml
config/prod/sc-serverless-launchrole.yaml

Setup service catalog policies and roles from the
AWS SC reference architecture documentation
https://github.com/aws-samples/aws-service-catalog-reference-architectures/tree/master/iam

Setup policies and roles for service catalog

---

config/prod/sc-vpc-constraint.yaml
templates/sc-vpc-constraint.yaml

Constrains the linux product to one vpc
Constrains the linux product subnet to subnets of that vpc

Add vpc constraint

---

config/prod/sc-vpc-constraint.yaml

remove vpc constraint, it is no longer needed.

Remove vpc constraint

---

.gitignore
README.md

This is really just to trigger a build.

Add Pipfile to .gitignore

---

.travis.yml

Set debug flag on sceptre call

Set debug flag on sceptre call

---

config/prod/cfn-ssm-param-macro.yaml

deploy the cfn-ssm-param-macro lambda

deploy the cfn-ssm-param-macro lambda

---

config/prod/test-ssm-macro-bucket.yaml
templates/test-ssm-macro-bucket.yaml

Test the ssm param macro

---

config/prod/sc-tag-options.yaml

Add more project tags

---

config/prod/sc-tag-options.yaml

Tags alphabetized to make easier to use by humans

Sort tags so that humans can easily read

---

config/prod/sc-tag-options.yaml

add new portfolios
add new account emails

Add new portfolios and owner emails to tag options

---

templates/accounts.yaml
templates/sc-accounts.yaml

Add Xa and Aaron as admins
Add Kelsey as SC user

Add more accounts

---

templates/sc-accounts.yaml

Add accounts for Xindi and Lea to use Service Catalog

Add sc accounts for Xindi and Lea

---

templates/accounts.yaml

I'm planning to help out on the dev side and so am requesting an infrastructure iam user account... not sure that I need admin, but probably. Please edit if you think otherwise. 
Also, I wonder if we should add @tthyer to the infra-oversight-commit GH group so a review can be requested more easily? 
Passes pre-commit all

Adding ahayden user with admin

---

.travis.yml
config/prod/sc-portfolio-ec2-development.yaml
config/prod/sc-portfolio-ec2.yaml
config/prod/sc-portfolio-s3-basic-development.yaml
config/prod/sc-portfolio-s3-basic.yaml

Use sceptre-date-resolver to set StackDatetime parameter in EC2 portfolios
This PR depends on https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/78 and https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/79 -- do not merge this first

Use sceptre-date-resolver to set StackDatetime parameter in EC2 portfolios

---

templates/sc-accounts.yaml

IAM users who did not set up their accounts or request more time have been removed.

Removed IAM users who did not set up MFA

---

templates/sc-accounts.yaml

PR Checklist:
[ ] Describe and explain your intentions for this change
[ ] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`

Add resource for Thomas Schaffter

---

config/dev/sc-tag-options.yaml

adds separate stack with very limited tag options for dev portfolios

Add distinct tag options stack for dev portfolios

---

config/dev/sc-tag-options-dev.yaml
templates/sc-tag-options.j2

Make separate stack for dev
Make OwnerEmails optional

Fix dev tag options

---

config/prod/sc-tag-options.yaml

Adding aaron.hayden tag option

---

config/prod/cfn-cr-bucket-tagger.yaml
config/prod/set-bucket-tags-macro.yaml

Add bucket tagger custom resource macro to scipoolprod. This depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-bucket-tagger/pull/1.

Add bucket tagger custom resource

---

README.md
config/config.yaml

changed name of template library from scipoolprod-sc-lib-infra to service-catalog-library

[SC-119] Change template library name

---

config/develop/cfn-cr-sc-actions-provider.yaml
config/develop/sc-ec2-actions.yaml
config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/develop/sc-product-ec2-linux-jumpcloud.yaml
config/develop/sc-product-ec2-windows-jumpcloud.yaml
config/prod/cfn-sc-actions-provider.yaml
config/prod/sc-ec2-actions.yaml

To make things a little easier to understand we rename the custom
resource instance from cfn-sc-actions-provider to
cfn-cr-sc-actions-provider.
This PR depends on PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/147

[SC-26] Rename lambda and update references

---

config/develop/cfn-cr-sc-bucket-policy.yaml
config/prod/cfn-cr-sc-bucket-policy.yaml

Add stacks for new custom resource that creates BucketPolicy
Depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/1

Add cfn-cr-sc-bucket-policy stacks

---

config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/develop/sc-product-ec2-linux-jumpcloud.yaml
config/develop/sc-product-ec2-windows-jumpcloud.yaml
config/develop/sc-product-s3-private-enc.yaml
config/develop/sc-product-s3-synapse.yaml
config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/prod/sc-product-ec2-linux-jumpcloud.yaml
config/prod/sc-product-ec2-windows-jumpcloud.yaml
config/prod/sc-product-s3-private-enc.yaml
config/prod/sc-product-s3-synapse.yaml

Reverts Sage-Bionetworks/scipool-infra#124
This will re-add StackDatetime setting into all products.

Revert "Remove StackDatetime from product stack configurations"

---

config/develop/sc-portfolio-ec2-external.yaml
config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/develop/sc-product-ec2-linux-jumpcloud.yaml
config/develop/sc-product-ec2-windows-jumpcloud.yaml
config/develop/sc-product-s3-private-enc.yaml
config/develop/sc-product-s3-synapse.yaml
config/prod/sc-portfolio-ec2-external.yaml
config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/prod/sc-product-ec2-linux-jumpcloud.yaml
config/prod/sc-product-ec2-windows-jumpcloud.yaml
config/prod/sc-product-s3-private-enc.yaml
config/prod/sc-product-s3-synapse.yaml

This PR depends on PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/203
We no longer pass in PortfolioId instead we do a cross stack reference
to it to accomodate multiple portfolios

[SC-65] External EC2 products

---

config/develop/sc-portfolio-ec2-external.yaml
config/develop/sc-portfolio-ec2.yaml
config/prod/sc-portfolio-ec2-external.yaml
config/prod/sc-portfolio-ec2.yaml

We now support multiple portfolios so providing better
description will help make it easier to identify in
the AWS console.

[SC-65] Update EC2 portfolio names and descriptions

---

config/develop/cfn-ssm-param-policy.yaml
config/develop/get-role-policy.yaml
config/develop/sc-ec2vpc-launchrole.yaml
config/develop/sc-enduser-iam.yaml
config/develop/sc-s3-launchrole.yaml
config/prod/cfn-ssm-param-policy.yaml
config/prod/get-role-policy.yaml
config/prod/sc-ec2vpc-launchrole.yaml
config/prod/sc-enduser-iam.yaml
config/prod/sc-s3-launchrole.yaml
templates/cfn-ssm-param-policy.yaml
templates/get-role-policy.yaml
templates/sc-ec2vpc-launchrole.yaml
templates/sc-enduser-iam.yaml
templates/sc-s3-launchrole.yaml

Start the process of moving libraries to this repo per SC-192.
The first to move over are the IAM templates.

[SC-192] Refactor SC library IAM templates

---

config/develop/sc-tag-options.yaml
config/prod/sc-tag-options.yaml
templates/sc-tag-options.j2

* Moving SC tag option libraries to this repo per SC-192.
* Remove unused tag option dev file

[SC-192] Refactor SC tag option library templates

---

config/develop/sc-portfolio-s3-basic.yaml
config/develop/sc-product-s3-private-enc.yaml
config/develop/sc-product-s3-synapse.yaml
config/prod/sc-portfolio-s3-basic.yaml
config/prod/sc-product-s3-private-enc.yaml
config/prod/sc-product-s3-synapse.yaml
templates/sc-portfolio-s3-basic.yaml
templates/sc-product-s3-private-enc.yaml
templates/sc-product-s3-synapse.yaml

Moving libraries to this repo per SC-192.

[SC-192] Refactor SC library S3 templates

---

config/develop/sc-ec2-actions.yaml
config/develop/sc-portfolio-ec2-external.yaml
config/develop/sc-portfolio-ec2.yaml
config/develop/sc-product-assoc-ec2-linux-jumpcloud-notebook.yaml
config/develop/sc-product-assoc-ec2-linux-jumpcloud-workflows.yaml
config/develop/sc-product-assoc-ec2-linux-jumpcloud.yaml
config/develop/sc-product-assoc-ec2-linux-windows-jumpcloud.yaml
config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/develop/sc-product-ec2-linux-jumpcloud.yaml
config/develop/sc-product-ec2-windows-jumpcloud.yaml
config/prod/sc-ec2-actions.yaml
config/prod/sc-portfolio-ec2-external.yaml
config/prod/sc-portfolio-ec2.yaml
config/prod/sc-product-assoc-ec2-linux-jumpcloud-notebook.yaml
config/prod/sc-product-assoc-ec2-linux-jumpcloud-workflows.yaml
config/prod/sc-product-assoc-ec2-linux-jumpcloud.yaml
config/prod/sc-product-assoc-ec2-linux-windows-jumpcloud.yaml
config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/prod/sc-product-ec2-linux-jumpcloud.yaml
config/prod/sc-product-ec2-windows-jumpcloud.yaml
templates/sc-ec2-action-associations.yaml
templates/sc-ec2-actions.yaml
templates/sc-portfolio-ec2-external.yaml
templates/sc-portfolio-ec2.yaml
templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
templates/sc-product-ec2-linux-jumpcloud-workflows.yaml
templates/sc-product-ec2-linux-jumpcloud.yaml
templates/sc-product-ec2-windows-jumpcloud.yaml

Moving SC EC2 libraries to this repo per SC-192.

[SC-192] Refactor SC EC2 library templates

---

config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/develop/sc-product-ec2-linux-jumpcloud.yaml
config/develop/sc-product-ec2-windows-jumpcloud.yaml
config/develop/sc-product-s3-private-enc.yaml
config/develop/sc-product-s3-synapse.yaml
config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
config/prod/sc-product-ec2-linux-jumpcloud.yaml
config/prod/sc-product-ec2-windows-jumpcloud.yaml
config/prod/sc-product-s3-private-enc.yaml
config/prod/sc-product-s3-synapse.yaml

Pin versioned SC libraries from https://github.com/Sage-Bionetworks/service-catalog-library/releases/tag/v1.0.0

[SC-192] Pin versioned SC libraries

---

config/develop/sc-kms-key.yaml
config/prod/sc-kms-key.yaml
templates/sc-kms-key.yaml

- creates new shared key
- adds the minimal "default" Key Policy that allows IAM policies to be created which allow key access
- creates an IAM policy for that purpose

Add a KMS key for data shared by Service Catalog resources and apps

---

config/develop/cfn-cr-alb-rule.yaml
config/prod/cfn-cr-alb-rule.yaml

Adds develop and prod sceptre configurations for new custom resource that adds listener rules for an ALB
Depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/1 https://github.com/Sage-Bionetworks/scipool-infra/pull/148

Add configurations for ALB rule creating custom resource

---

config/develop/sc-kms-key.yaml
config/prod/sc-kms-key.yaml

Add stack tags and this common kms key depends on the
idp being setup.

add stack dependencies and tags

---

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
templates/sc-product-ec2-linux-jumpcloud-workflows.yaml
templates/sc-product-ec2-linux-jumpcloud.yaml

This is a redo of commit ce52e29753 which was [reverted](5b0aa1fd). It was reverted
because the template URL reference was incorrect.  This PR contain
the product update with the fix to the URL reference to the file.

[SC-100] Fix update products

---

config/develop/alb-notebook-access-logsbucket.yaml
config/prod/alb-notebook-access-logsbucket.yaml
templates/alb-notebook-access-logsbucket.yaml

This PR just creates a logging bucket in the appropriate scipool account to hold access logs from the notebook ALBs.

SC-211/alb logsbucket

---

config/develop/sc-tag-options.yaml
config/prod/sc-tag-options.yaml

add new project tag options

---

config/develop/sc-tag-options.yaml
config/prod/sc-tag-options.yaml

We'll need tags for Governance work in SC.

Adding Governance general ACT tag

---

templates/sc-product-ec2-linux-jumpcloud-workflows.yaml

create new version for change in user added to docker group

[SC-226] New workflows EC2 version v1.1.4

---

templates/sc-product-ec2-linux-jumpcloud-workflows.yaml

Adds new workflows version with the fix for ssm-user (creating the user to circumvent its delayed creation by ssm agent) from service-catalog-library

[SC-226] New workflows EC2 version v1.1.5 adds ssm-user before adding it to the docker group

---

.cfnlintrc
.pre-commit-config.yaml
templates/develop/lambda-budgets/budget-rules.yaml

- use real email address 
- replace `.cfnlintrc` with exclude pattern in `.pre-commit-config.yaml`

[SC-88] Update email in rules config for dev budgets lambda to a real address

---

utils/manage_ec2.py

Script to stop EC2 instances when SC user buget is exceeded.

[SC-201] Utility script to manage EC2s

---

config/develop/lambda-send-budget-alert.yaml
config/prod/lambda-send-budget-alert.yaml

This PR adds the sceptre configuration for lambda-send-budget-alert

SC-213 adding sceptre configuration for lambda-send-budget-alert

---

config/develop/cfn-cr-synapse-tagger.yaml
config/prod/cfn-cr-synapse-tagger.yaml

depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#1

[SC-190] install synapse tagger custom resource

---

config/develop/cfn-cr-synapse-tagger.yaml
config/prod/cfn-cr-synapse-tagger.yaml

pin to a version so we can continue to develop on master branch

[SC-190] pin to a cfn-cr-synapse-tagger lambda version

---

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
templates/sc-product-ec2-linux-jumpcloud-workflows.yaml
templates/sc-product-ec2-linux-jumpcloud.yaml
templates/sc-product-ec2-windows-jumpcloud.yaml
templates/sc-product-s3-private-enc.yaml
templates/sc-product-s3-synapse.yaml

* update to https://github.com/Sage-Bionetworks/service-catalog-library/releases/tag/v1.1.8
* fix up some produc descriptions
* put fixes for SC-133, SC-151, and SC-168 into service

update SC product versions

---

templates/strides/jumpcloud-idp.yaml

Forgot to add these files on previous commit 1426516796

Add templates for jumpcloud IDP

---

config/strides/stridespoolvpc.yaml

The VPC name is gonna be `stridespoolvpc`

[SC-227] Setup a VPC for strides account

---

config/strides/peer-vpn-stridespoolvpc.yaml

This is to setup integration with our Sage VPN

[SC-227] Setup Peering to Sage VPN VPC

---

config/develop/cfn-cr-synapse-tagger.yaml
config/prod/cfn-cr-synapse-tagger.yaml

depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#18

[SC-248] Update cfn-cf-synapse-tagger

---

config/prod/maintenance.yaml
config/strides/maintenance.yaml

This PR adds the EC2 maintenance tasks to the prod and strides accounts.
Passes pre-commit checks

add maintenance tasks to new accounts

---

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
templates/sc-product-ec2-linux-jumpcloud-workflows.yaml
templates/sc-product-ec2-linux-jumpcloud.yaml
templates/sc-product-ec2-windows-jumpcloud.yaml
templates/sc-product-s3-private-enc.yaml
templates/sc-product-s3-synapse.yaml

this updates the version to include params in mappings.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/234

update service catalog library version

---

templates/sc-product-ec2-linux-jumpcloud-workflows.yaml

new version of workflows product to update workflows software

[SC-249] update software in workflows product

---

config/develop/sc-tag-options-external.yaml
config/develop/sc-tag-options.yaml
config/prod/sc-tag-options-external.yaml
config/prod/sc-tag-options.yaml
config/strides/sc-tag-options-external.yaml
config/strides/sc-tag-options.yaml
sc-tag-options/external/Departments.json
sc-tag-options/external/Projects.json
sc-tag-options/internal/Departments.json
sc-tag-options/internal/Projects.json

Renove tag option duplication by exporting them to a file and importing
them to templates in multiple environments.

DRY refactor of tag options

---

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml

depends on Sage-Bionetworks/service-catalog-library#237

[SC-241] update apache script

---

templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
templates/sc-product-ec2-linux-jumpcloud-workflows.yaml
templates/sc-product-ec2-linux-jumpcloud.yaml
templates/sc-product-ec2-windows-jumpcloud.yaml

depends on Sage-Bionetworks/service-catalog-library#236

[SC-241] Update SC library version

---

config/develop/cfn-cr-synapse-tagger.yaml
config/prod/cfn-cr-synapse-tagger.yaml
config/strides/cfn-cr-synapse-tagger.yaml

depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#23

Update cfn-cr-synapse-tagger version

---

config/develop/lambda-sc-cost-meter.yaml
config/prod/lambda-sc-cost-meter.yaml
config/strides/lambda-sc-cost-meter.yaml

Deploy the lambda-sc-cost-meter to all accounts running the service
catalog
depends on Sage-Bionetworks-IT/lambda-sc-cost-meter#2

Install the cost meter lambda

---

config/develop/cfn-cr-synapse-tagger.yaml
config/prod/cfn-cr-synapse-tagger.yaml
config/strides/cfn-cr-synapse-tagger.yaml

depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#26

updatee cfn-cr-synapse-tagger version

---

.travis.yml

The sceptre-file-resolver has beeen moved.  Install from the new
location.

Sceptre file resolver moved.
